/**
 * Returns fields array from input models
 * It returns only those columns which does not have a auto flag in the model
 * auto flag will be available for those columns, for which values will be generated by database
 * Like: Auto Increment id in MySQL
 * @param model : JSON
 * @param prefix : String
 */
const get = (model, prefix) => {
  let fields = [];
  prefix = prefix ? `${prefix}.` : '';
  for (let column of model.columns) {
    if (!column.auto) {
      fields.push(`${prefix}${column.name}`);
    }
  }

  return fields;
};


module.exports = {
  get
};
